describe('template spec', () => {
  it('Click Content demoblaze', () => {
    cy.visit('https://www.demoblaze.com/')
    cy.get('#login2').click()
    cy.get('#loginusername').type('windadyahayu').should('be.visible')
    cy.wait(5)
    cy.get('#loginpassword').type('1234')
    cy.wait(5)
    cy.get('#logInModal > .modal-dialog > .modal-content > .modal-footer > .btn-primary').click()
    cy.wait(2)
    cy.get(':nth-child(1) > .card > :nth-child(1) > .card-img-top').click()
    cy.wait(2)
    cy.get('.col-sm-12 > .btn').click()
    cy.get(':nth-child(4) > .nav-link').click()
    cy.wait(5)
    cy.get('.col-lg-1 > .btn').click()
    cy.wait(2)
    cy.get('#name').type('windadyahayu').should('be.visible')
    cy.wait(20)
    cy.get('#country').type('Indonesia').should('be.visible')
    cy.wait(5)
    cy.get('#city').type('Bogor').should('be.visible')
    cy.wait(5)
    cy.get('#card').type('010203').should('be.visible')
    cy.wait(5)
    cy.get('#month').type('January').should('be.visible')
    cy.wait(5)
    cy.get('#year').type('2023').should('be.visible')
    cy.wait(5)
    cy.get('#orderModal > .modal-dialog > .modal-content > .modal-footer > .btn-primary').click()
    cy.wait(5)
    cy.get('.confirm').click()

  })
})